site_name: "Tigray Knowledge Base – Ternafit"
site_url: https://tigray.ternafit.org
site_description: "The most comprehensive, authoritative, and multimedia-rich knowledge base on Tigray, Ethiopia"
site_author: "Ternafit NGO"
# Force rebuild for Twitter handle deployment
docs_dir: docs
# repo_url: https://github.com/yosephdev/tigray.ternafit.org
# repo_name: yosephdev/tigray.ternafit.org
# edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/images/logo-primary.svg
  favicon: assets/images/favicon.svg
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - content.tooltips
    - header.autohide
  font:
    text: Inter
    code: JetBrains Mono

nav:
  - Home: 
    - index.md
    - About Ternafit: about.md
    - Contribute: contribute.md
  
  # MAIN SECTIONS (Original + Gemini Strategic Framework)
  - Geography: 
    - Overview: 01-geography.md
    - Interactive Maps: geography/maps.md
    - Geography & Topography: land/geography-topography.md
  - Demographics: 
    - Overview: 02-demographics.md
    - Population Data: demographics/population.md
  - Economy: 03-economy.md
  - Education & Health: 04-edu-health.md
  - History & Culture: 
    - Overview: 05-history-culture.md
    - Ancient Tigray: history/ancient-tigray.md
    - Historical Figures:
      - King Ezana of Axum: figures/king-ezana.md
      - Emperor Yohannes IV: figures/yohannes-iv.md
      - Ras Alula Aba Nega: figures/alula-aba-nega.md
      - Abreha and Atsbeha: figures/abreha-atsbeha.md
      - Queen of Sheba (Makeda): figures/queen-of-sheba.md
      - Queen Gudit: figures/queen-gudit.md
      - Dr. Tedros Adhanom Ghebreyesus: figures/tedros-adhanom.md
      - Meles Zenawi: figures/meles-zenawi.md
      - Seyum Mesfin: figures/seyum-mesfin.md
      - Gebrehiwot Baykedagn: figures/gebrehiwot-baykedagn.md
      - Dejazmach Sabagadis: figures/dejazmach-sabagadis.md
      - Ras Seyum Mengesha: figures/ras-seyum-mengesha.md
      - Ras Woldemichael Gugsa: figures/ras-woldemichael-gugsa.md
    - Culture & People: culture/tigrayan-people.md
  - War Memorial: 
    - Overview: 06-war-memorial.md
    - The Tigray War (2020-2022):
      - The Path to War: war/path-to-war.md
      - Conflict Overview: war/conflict-overview.md
      - Human Rights Atrocities: war/human-rights-atrocities.md
      - Humanitarian Crisis: war/humanitarian-crisis.md
      - Economic Devastation: war/economic-devastation.md
      - The Fragile Peace: war/fragile-peace.md
      - War Timeline: war/timeline.md
      - Memorial: war/memorial.md
  - Current Affairs: 
    - Overview: 07-current-affairs.md
    - Latest News: current/news.md
  - Downloads: 
    - Standard: 08-downloads.md
    - Enhanced: 08-downloads-enhanced.md
  
  # RESOURCES (Gemini Digital Library Recommendation)
  - Resources:
    - Digital Library: resources/digital-library.md
    - Bibliography: resources/bibliography.md
    - Tags: tags.md
  
  # DEVELOPMENT
  - Development:
    - Stub Articles: stubs.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/ternafit
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/ternafit
    - icon: fontawesome/brands/twitter
      link: https://x.com/infoternafit
    - icon: fontawesome/solid/globe
      link: https://ternafit.org
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

copyright: >
  Copyright &copy; 2025 Ternafit NGO –
  <a href="#__consent">Change cookie settings</a>

plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - tags:
      tags_file: tags.md
  - table-reader
  - awesome-pages
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      custom_format: "%d. %B %Y"
      timezone: Europe/Stockholm
      locale: en
      fallback_to_build_date: true
  - rss:
      match_path: "docs/07-current-affairs.md"
      date_from_meta:
        as_creation: "date"
      categories:
        - categories
        - tags
      comments_path: "#__comments"

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: yosephdev
      repo: tigray.ternafit.org
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - https://unpkg.com/plotly.js@2.27.0/dist/plotly.min.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
  - assets/js/charts.js
  - assets/js/enhanced.js

extra_css:
  - assets/css/custom.css
  - assets/css/enhanced.css
  - https://unpkg.com/leaflet@1.9.4/dist/leaflet.css
