site_name: "Tigray Knowledge Base – TernaFit"
site_url: https://tigray.ternafit.org
docs_dir: docs
repo_url: https://github.com/yosephdev/tigray.ternafit.org
theme:
  name: material
  logo: assets/ternafit_logo.svg
  palette:
    - scheme: default
      primary: deep orange
  features:
    - navigation.tabs
    - navigation.sections
nav:
  - Home: index.md
  - Geography: 01-geography.md
  - Demographics: 02-demographics.md
  - Economy: 03-economy.md
  - Education & Health: 04-edu-health.md
  - History & Culture: 05-history-culture.md
  - Tigray War & Memorial: 06-war-memorial.md
  - Current Affairs: 07-current-affairs.md
  - Downloads: 08-downloads.md
extra:
  version: 2025-08-13
